name: Python Flask Application CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on:
      - codebuild-readinglist-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Lint code with pylint
      - name: Run pylint
        run: |
          pylint app/**/*.py run.py .ebextensions/*.py --fail-under=7

      # Step 5: Set up Docker Compose
      # - name: Set up Docker Compose
      #   uses: docker/setup-compose-action@v1

      # Step 6: Run pytest with coverage
      - name: Run pytest with coverage
        run: |
          pytest --cov=app --cov-report=xml --cov-fail-under=70 --disable-pytest-warnings
