name: Python Flask Application CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on:
      #- codebuild-readinglist-${{ github.run_id }}-${{ github.run_attempt }}
      - ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5.5.0
        with:
          python-version: '3.11'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade --no-cache-dir pip
          pip install --no-cache-dir -r requirements.txt

      # Step 4: Lint code with pylint
      - name: Run pylint
        run: |
          pylint app/**/*.py run.py .ebextensions/*.py --fail-under=7 | tee pylint.report.txt

      # Step 5: Run pytest with coverage
      - name: Run pytest with coverage
        run: |
          pytest --cov=app --cov-report=xml --cov-report=html --cov-fail-under=70
